#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2026 Anand Jain <asj@kernel.org>.  All Rights Reserved.
#
# FS QA Test 800
#
# Verify if the kernel or userspace becomes confused when two block devices
# share the same fid/fsid/uuid. Create inotify on both original and cloned
# filesystem. Monitor the notification in the respective logs.

. ./common/preamble

_begin_fstest auto quick mount clone

_require_test
_require_block_device $TEST_DEV
_require_loop
_require_command "$INOTIFYWAIT_PROG" inotifywait

_cleanup()
{
	cd /
	[[ -n $pid1 ]] && { kill -TERM "$pid1" 2> /dev/null; wait $pid1; }
	[[ -n $pid2 ]] && { kill -TERM "$pid2" 2> /dev/null; wait $pid2; }
	rm -r -f $tmp.*
	_unmount $mnt1 2>/dev/null
	_unmount $mnt2 2>/dev/null
	_loop_image_destroy "${devs[@]}" 2> /dev/null
}

devs=()
_loop_image_create_clone devs
mkdir -p $TEST_DIR/$seq
mnt1=$TEST_DIR/$seq/mnt1
mnt2=$TEST_DIR/$seq/mnt2
mkdir -p $mnt1
mkdir -p $mnt2

_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[0]} $mnt1 || \
						_fail "Failed to mount dev1"
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[1]} $mnt2 || \
						_fail "Failed to mount dev2"

log1=$tmp.inotify1
log2=$tmp.inotify2

pid1=""
pid2=""
echo "Setup inotify watchers on both mnt1 and mnt2"
$INOTIFYWAIT_PROG -m -e create --format '%f' $mnt1 > $log1 2>&1 &
pid1=$!
$INOTIFYWAIT_PROG -m -e create --format '%f' $mnt2 > $log2 2>&1 &
pid2=$!
sleep 2

echo "Trigger file creation on mnt1"
touch $mnt1/file_on_mnt1
sync
sleep 1

echo "Trigger file creation on mnt2"
touch $mnt2/file_on_mnt2
sync
sleep 1

echo "Verify inotify isolation"
kill $pid1 $pid2
wait $pid1 $pid2 2>/dev/null
pid1=""
pid2=""

if grep -q "file_on_mnt1" $log1 && ! grep -q "file_on_mnt2" $log1; then
	echo "SUCCESS: mnt1 events isolated."
else
	echo "FAIL: mnt1 inotify confusion!"
	[ ! -s $log1 ] && echo "  - mnt1 received no events."
	grep -q "file_on_mnt2" $log1 && echo "  - mnt1 received event from mnt2."
fi

if grep -q "file_on_mnt2" $log2 && ! grep -q "file_on_mnt1" $log2; then
	echo "SUCCESS: mnt2 events isolated."
else
	echo "FAIL: mnt2 inotify confusion!"
	[ ! -s $log2 ] && echo "  - mnt2 received no events."
	grep -q "file_on_mnt1" $log2 && echo "  - mnt2 received event from mnt1."
fi

status=0
exit
