#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2026 Anand Jain <asj@kernel.org>.  All Rights Reserved.
#
# FS QA Test 802
# Check that the cloned filesystem provides an f_fsid that is persistent
# across mount cycles if the block device maj:min remains unchanged.

. ./common/preamble

_begin_fstest auto quick mount clone

_require_test
_require_block_device $TEST_DEV
_require_loop

_fixed_by_fs_commit btrfs xxxxxxxxxxxx \
	"btrfs: use on-disk uuid for s_uuid in temp_fsid mounts"
_fixed_by_fs_commit btrfs xxxxxxxxxxxx \
	"btrfs: derive f_fsid from on-disk fsuuid and dev_t"

_cleanup()
{
	cd /
	rm -r -f $tmp.*
	umount $mnt1 $mnt2 2>/dev/null
	_loop_image_destroy "${devs[@]}" 2> /dev/null
}

# Setup base loop device and its clone
devs=()
_loop_image_create_clone devs
mkdir -p $TEST_DIR/$seq
mnt1=$TEST_DIR/$seq/mnt1
mnt2=$TEST_DIR/$seq/mnt2
mkdir -p $mnt1
mkdir -p $mnt2

# Mount both filesystems simultaneously using mandatory clone mount options
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[0]} $mnt1 || \
						_fail "Failed to mount dev1"
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[1]} $mnt2 || \
						_fail "Failed to mount dev2"

# Capture baseline filesystem IDs for comparison
fsid_scratch=$(stat -f -c "%i" $mnt1)
fsid_clone=$(stat -f -c "%i" $mnt2)

# Verify that the fsids remain stable after a mount cycle, even when the
# mount order is reversed.
echo "**** fsid after mount cycle ****"
_unmount $mnt1
_unmount $mnt2
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[1]} $mnt2 || \
						_fail "Failed to mount dev2"
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[0]} $mnt1 || \
						_fail "Failed to mount dev1"

# Compare post mount-cycle values against the baseline
stat -f -c "%i" $mnt1 | sed -e "s/$fsid_scratch/FSID_SCRATCH/g"
stat -f -c "%i" $mnt2 | sed -e "s/$fsid_clone/FSID_CLONE/g"

status=0
exit
