#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2026 Anand Jain <asj@kernel.org>.  All Rights Reserved.
#
# FS QA Test 803
# Verify how libblkid resolve devices when multiple devices sharing the
# same FSUUID.

. ./common/preamble
. ./common/filter

_begin_fstest auto quick mount clone

_require_test
_require_block_device $TEST_DEV
_require_loop

_cleanup()
{
	cd /
	rm -r -f $tmp.*
	umount $mnt1 $mnt2 2>/dev/null
	_loop_image_destroy "${devs[@]}" 2> /dev/null
}

filter_pool()
{
	sed -e "s|${devs[0]}|DEV1|g" -e "s|${mnt1}|MNT1|g" \
	    -e "s|${devs[1]}|DEV2|g" -e "s|${mnt2}|MNT2|g" | _filter_spaces
}

print_info()
{
	local mntpt=$1
	local tgt=$(findmnt -no SOURCE $mntpt)
	local fsuuid=$(blkid -s UUID -o value $tgt)

	echo "mntpt=$mntpt tgt=$tgt fsuuid=$fsuuid" >> $seqres.full
	echo
	findmnt -o SOURCE,TARGET,UUID "$tgt" | tail -n +2 | \
				sed -e "s/${fsuuid}/FSUUID/g" | filter_pool
	awk -v dev="$tgt" '$1 == dev { print $1, $2 }' /proc/self/mounts | \
								filter_pool
	df --all --output=source,target "$tgt" | tail -n +2 | filter_pool
}

devs=()
_loop_image_create_clone devs
mkdir -p $TEST_DIR/$seq
mnt1=$TEST_DIR/$seq/mnt1
mnt2=$TEST_DIR/$seq/mnt2
mkdir -p $mnt1
mkdir -p $mnt2

_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[0]} $mnt1 || \
						_fail "Failed to mount dev1"
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[1]} $mnt2 || \
						_fail "Failed to mount dev2"

print_info $mnt1
print_info $mnt2

echo
echo "**** mount cycle ****"
_unmount $mnt1
_unmount $mnt2
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[1]} $mnt2 || \
						_fail "Failed to mount dev2"
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[0]} $mnt1 || \
						_fail "Failed to mount dev1"

print_info $mnt1
print_info $mnt2

status=0
exit
