#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2026 Anand Jain <asj@kernel.org>.  All Rights Reserved.
#
# FS QA Test 803
# Check if the mountinfo based findmnt would resolve to the common uuid
# as per the blkid (libblkid based).

. ./common/preamble
. ./common/filter

_begin_fstest auto quick mount clone

_require_test
_require_block_device $TEST_DEV
_require_loop

_cleanup()
{
	cd /
	rm -r -f $tmp.*
	umount $mnt1 $mnt2 2>/dev/null
	_loop_image_destroy "${devs[@]}" 2> /dev/null
}

# Normalize pool devices and mount points names
filter_pool()
{
	sed -e "s|${devs[0]}|DEV1|g" -e "s|${mnt1}|MNT1|g" \
	    -e "s|${devs[1]}|DEV2|g" -e "s|${mnt2}|MNT2|g" | _filter_spaces
}

# Setup base loop device and its clone
devs=()
_loop_image_create_clone devs
mkdir -p $TEST_DIR/$seq
mnt1=$TEST_DIR/$seq/mnt1
mnt2=$TEST_DIR/$seq/mnt2
mkdir -p $mnt1
mkdir -p $mnt2

# Get the uuid from the source device
fsuuid=$(blkid -s UUID -o value ${devs[0]})

# Mount both identical UUID filesystems simultaneously
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[0]} $mnt1 || \
						_fail "Failed to mount dev1"
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[1]} $mnt2 || \
						_fail "Failed to mount dev2"

findmnt -o SOURCE,TARGET,UUID "${devs[0]}" | tail -n +2 | \
				sed -e "s/${fsuuid}/FSUUID/g" | filter_pool
findmnt -o SOURCE,TARGET,UUID "${devs[1]}" | tail -n +2 | \
				sed -e "s/${fsuuid}/FSUUID/g" | filter_pool

# Btrfs assigned a random uuid for the clone fs before the fix.
# Cycle mounts and reverse the initialization (source and clone fs) order.
echo "**** mount cycle ****"
_unmount $mnt1
_unmount $mnt2
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[1]} $mnt2 || \
						_fail "Failed to mount dev2"
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[0]} $mnt1 || \
						_fail "Failed to mount dev1"

findmnt -o SOURCE,TARGET,UUID "${devs[0]}" | tail -n +2 | \
				sed -e "s/${fsuuid}/FSUUID/g" | filter_pool
findmnt -o SOURCE,TARGET,UUID "${devs[1]}" | tail -n +2 | \
				sed -e "s/${fsuuid}/FSUUID/g" | filter_pool

status=0
exit
