#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2026 Anand Jain <asj@kernel.org>.  All Rights Reserved.
#
# FS QA Test No. 805

. ./common/preamble

_begin_fstest auto quick exportfs clone

_require_test
_require_block_device $TEST_DEV
_require_exportfs
_require_loop
_require_test_program "open_by_handle"

_cleanup()
{
	cd /
	rm -r -f $tmp.*
	_unmount $mnt1 2>/dev/null
	_unmount $mnt2 2>/dev/null
	_loop_image_destroy "${devs[@]}" 2> /dev/null
}

# Create test dir and test files, encode file handles and store to tmp file
create_test_files()
{
	rm -rf $testdir
	mkdir -p $testdir
	$here/src/open_by_handle -cwp -o $tmp.handles_file $testdir $NUMFILES
}

# Decode file handles loaded from tmp file
test_file_handles()
{
	local opt=$1
	local when=$2

	echo test_file_handles after $when
	$here/src/open_by_handle $opt -i $tmp.handles_file $mnt2 $NUMFILES
}

devs=()
_loop_image_create_clone devs
mkdir -p $TEST_DIR/$seq
mnt1=$TEST_DIR/$seq/mnt1
mnt2=$TEST_DIR/$seq/mnt2
mkdir -p $mnt1
mkdir -p $mnt2

_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[0]} $mnt1 || \
						_fail "Failed to mount dev1"
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[1]} $mnt2 || \
						_fail "Failed to mount dev2"

NUMFILES=1
testdir=$mnt2/testdir

# Decode file handles of files/dir after cycle mount
create_test_files

_unmount $mnt1
_unmount $mnt2
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[1]} $mnt2 || \
						_fail "Failed to mount dev2"
_mount $(_common_dev_mount_options) $(_clone_mount_option) ${devs[0]} $mnt1 || \
						_fail "Failed to mount dev1"

test_file_handles -rp "cycle mount"

status=0
exit
