#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025 Oracle.  All Rights Reserved.
#
# FS QA Test 888
#
# Test if the device paths are compatible with systemd udev tools like
# mount -a and findmnt.
# Provide the device dm path to the mount command and verify that it is
# correctly resolved to the mapper path in the kernel.
#
. ./common/preamble
_begin_fstest auto

node="fstests_${seq}"

_cleanup()
{
	cd /
	rm -r -f $tmp.*

	sed -i "\|[[:space:]]$SCRATCH_MNT[[:space:]]|d" /etc/fstab
	_systemd_installed && _systemd_reload

	_unmount $SCRATCH_MNT > /dev/null 2>&1
	udevadm control --start-exec-queue
	_dmsetup_remove $node
}

. ./common/systemd
. ./common/filter

_require_scratch
_require_block_device $SCRATCH_DEV
_require_dm_target linear

# The btrfs-progs commit prevents the bug from manifesting.
[ "$FSTYP" = btrfs ] && _fixed_by_git_commit btrfs-progs XXXXXXXXXXXX \
		"btrfs-progs: fix inconsistency in device path handling"
[ "$FSTYP" = btrfs ] && _fixed_by_kernel_commit XXXXXXXXXXXX \
		"btrfs: pass device path update from mount thread"

filter_mapper()
{
	sed -e "s,\B$scratch_mapper_dev,MAPPER_PATH,g" |\
		sed -e "s,/dev/dm-[^ ]*,DM_PATH,g" |\
		_filter_scratch
}

#size doesn't matter just create it to the device size
sectors=$(blockdev --getsz $SCRATCH_DEV)
table="0 $sectors linear  $SCRATCH_DEV 0"
_dmsetup_create $node --table "$table" || _fail "setup dm device failed"

scratch_mapper_dev=/dev/mapper/$node
scratch_dm_dev=$(realpath ${scratch_mapper_dev})

# Block external triggers that alter the device path inside the kernel,
# they are unreliable.
udevadm control --stop-exec-queue
_mkfs_dev $scratch_dm_dev

# mount resolves dm path to its mapper path
_mount --verbose $scratch_dm_dev $SCRATCH_MNT | filter_mapper

fsid=$(findmnt -n -o UUID ${scratch_dm_dev})
blkid --uuid ${fsid} | filter_mapper
findmnt --source UUID=${fsid} --noheadings --output SOURCE | filter_mapper
cat /proc/self/mounts | grep ${SCRATCH_MNT} | \
				$AWK_PROG '{print $1" "$2}' | filter_mapper

echo "UUID=${fsid} ${SCRATCH_MNT} $FSTYP defaults 0 0" >> /etc/fstab
_systemd_installed && _systemd_reload
_mount --verbose -a | grep $SCRATCH_MNT | filter_mapper

status=0
exit
