#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025 Oracle.  All Rights Reserved.
#
# FS QA Test 334
#
# Verify sysfs knob input syntax for allocation/data/chunk_size
#
. ./common/preamble
_begin_fstest auto quick

. ./common/filter

_require_fs_sysfs_attr $TEST_DEV allocation/data/chunk_size
verify_sysfs_syntax $TEST_DEV allocation/data/chunk_size 256m

status=0
exit
