#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025 Anand Jain.
#
# FS QA Test btrfs/337
#
# Test ability to unmount after an EIO failure
#
. ./common/preamble
_begin_fstest auto quick

. ./common/filter
. ./common/fail_make_request

_require_scratch
_require_fail_make_request

_check_minimal_fs_size $(( 1024 * 1024 * 1024 ))
_scratch_mkfs "-b 1G" >> $seqres.full 2>&1

_scratch_mount

_allow_fail_make_request

echo "Step 1: writing with filed device:"
_bdev_fail_make_request $SCRATCH_DEV 1
$XFS_IO_PROG -f -c "pwrite -W -S 0xaa 0 8K" $SCRATCH_MNT/foobar | _filter_xfs_io
_bdev_fail_make_request $SCRATCH_DEV 0

# btrfs counts errors per IO, assuming the data is merged that'll be 1 IO, then
# the log tree block and then the log root tree block and then the super block.
# We should see at least 4 failed IO's, but with subpage blocksize we could see
# more if the log blocks end up on the same page, or if the data IO gets split
# at all.
$BTRFS_UTIL_PROG device stats $SCRATCH_DEV | \
	$AWK_PROG '/write_io_errs/ { print $2 }'

_disallow_fail_make_request

_scratch_unmount

# success, all done
status=0
exit
